default:
  env:
    python-version: 3.8
    poetry-version: 1.3.1
    poetry-home: ''
    poetry-path: ''
    poetry-cache-paths: |-
      ~/.local/share/pypoetry
      ~/.local/bin/poetry
    poetry-cache-key-fmt: 'poetry-{0}-{1}-python-{2}'
    venv-cache-key-fmt: 'venv-{0}-python-{1}-{2}'
