# This is used by the action below.
# https://github.com/dorny/paths-filter

lint:
  shared: &lint-shared
    - '.github/actions/read-yaml/action.yml'
    - '.github/settings/filters.yml'
    - '.github/workflows/lint.yml'
  # python scripts
  py-shared: &lint-py-shared
    - '.github/actions/setup-poetry/action.yml'
    - '.github/actions/setup-poetry-dependencies/action.yml'
    - '.github/settings/env.yml'
    - '.github/workflows/py_lint.yml'
    - 'poetry.lock'
    - 'pyproject.toml'
  py-lint: &lint-py-lint
    - 'tox.ini'
    - added|modified: '**/*.py'
  py:
    - *lint-shared
    - *lint-py-shared
    - *lint-py-lint
  # markdown files
  md-lint: &lint-md-lint
    - '.markdownlint.yml'
    - added|modified: '**/*.md'
  md:
    - *lint-shared
    - *lint-md-lint

test:
  shared: &test-shared
    - '.github/actions/read-yaml/action.yml'
    - '.github/actions/setup-poetry/action.yml'
    - '.github/actions/setup-poetry-dependencies/action.yml'
    - '.github/settings/filters.yml'
    - '.github/settings/test_matrix.yml'
    - '.github/workflows/test.yml'
    - 'poetry.lock'
    - 'pyproject.toml'
  tox: &test-tox
    - 'tox.ini'
  py: &test-py
    - added|modified: '**/*.py'
