default:
  matrix:
    os: [ubuntu-20.04, macos-latest, windows-latest]
    python-version: [3.7, 3.8]
    include:
      - os: ubuntu-20.04
        poetry-version: 1.3.1
        poetry-home: ''
        poetry-path: ''
        poetry-cache-paths: |-
          ~/.local/share/pypoetry
          ~/.local/bin/poetry

      - os: macos-latest
        poetry-version: 1.3.1
        poetry-home: ''
        poetry-path: ${HOME}/.local/bin
        poetry-cache-paths: |-
          ~/Library/Application Support/pypoetry
          ~/.local/bin/poetry

      - os: windows-latest
        poetry-version: 1.3.1
        poetry-home: ''
        poetry-path: ${APPDATA}\pypoetry\venv\Scripts
        poetry-cache-paths: |-
          ~\AppData\Roaming\pypoetry
          ~\AppData\Roaming\Python\Scripts\poetry.exe

    poetry-cache-key-fmt: ['poetry-{0}-{1}-python-{2}']
    venv-cache-key-fmt: ['venv-{0}-python-{1}-{2}']
    enable-coverage: ['true']
